# See config.example.yml for documentation.
object: orig/GKYE01/sys/main.dol
hash: 977533bb96e6a16e127946396489be1b4164ac42
symbols: config/GKYE01/symbols.txt
splits: config/GKYE01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
