# See config.example.yml for documentation.
object: orig/GKYJ01/sys/main.dol
hash: e901b9912af1b622c1f6d16fab6efe6cf505f108
symbols: config/GKYJ01/symbols.txt
splits: config/GKYJ01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
